version: "3.1"

services:
  template:
    build: .
    restart: on-failure
    environment:
      TZ: Europe/Berlin
      PORT: 80
      HOST: localhost
      ENV: prod
      LOG_LEVEL: 1
      DATABASE_HOST: database
      DATABASE_PORT: 5432
      DATABASE_USER: template
      DATABASE_PASSWORD: postgres
      DATABASE: template
    ports:
      - 80:80
    depends_on:
      database:
        condition: service_healthy
    links:
      - database

  database:
    image: postgres:13.3
    restart: unless-stopped
    hostname: database
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      TZ: Europe/Berlin
      POSTGRES_USER: template
      POSTGRES_PASSWORD: postgres

volumes:
  db-data:
